[package]
name = "embedded-bench"
version = "0.2.0"
edition = "2024"

[dependencies]
# d-engine = "0.2"
d-engine = { path = "../../d-engine" }

tokio = { version = "1", features = ["rt-multi-thread"] }
